accounts/urls.py
from django.urls import path

from .views import (
    LogInView, SignUpView, LogOutView,
    ProfileView, Home, userHistory, ChangeProfileView, deleteHistory, deleteAllHistory)

app_name="accounts"

urlpatterns=[

    path('', LogInView.as_view(), name='login'),
    path('login/', LogInView.as_view(), name='login'),
    path('log-out/', LogOutView.as_view(), name='logout'),
    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('home/', Home.as_view(), name='home'),
    path('userHistory/', userHistory.as_view(), name='history'),
    path('deleteHistory/<id>/', deleteHistory, name='delete_history'),
    path('deleteAllHistory/', deleteAllHistory, name='delete_all_history'),
    path('profile/', ProfileView, name='profile'),
    path('change_profile/', ChangeProfileView.as_view(), name='change_profile'),

]

django_calculator/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from accounts.views import LogInView, SignUpView, Home

urlpatterns=[
    path('', LogInView.as_view(), name='login'),
    path('login/', LogInView.as_view(), name='login'),
    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('home/', Home.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),

    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

accounts/models.py
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse


class MyUserQuerySet(models.query.QuerySet):
    def active(self):
        return self.filter(is_active=True)

    def featured(self):
        return self.filter(featured=True, active=True)


def firstName(value):
    if len(value) < 2 or len(value) > 20:
        raise ValidationError(
            "Should be 2-20 character.",
        )
    elif not value.isalpha():
        raise ValidationError(
            "Should be alphabets.",

        )


def nickName(value):
    if len(value) < 5 or len(value) > 20:
        raise ValidationError(
            "You Nick name should be 5-20 character.",
        )


def lastName(value):
    if len(value) < 2 or len(value) > 20:
        raise ValidationError(
            "Should be 2-20 character.",
        )
    elif not value.isalpha():
        raise ValidationError(
            "Should be alphabets.",
        )


class MyUserManager(BaseUserManager):
    def get_queryset(self):
        return MyUserQuerySet(self.model, using=self._db)

    def create_user(self, nick, first_name, last_name, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """

        user=self.model(
            nick=nick,
            first_name=first_name,
            last_name=last_name,
            is_admin=True,

        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, nick, first_name, last_name, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user=self.create_user(
            nick=nick,
            first_name=first_name,
            last_name=last_name,
            password=password,

        )
        return user

    def active(self):
        return self.filter(is_active=True)


class User(AbstractBaseUser):
    nick=models.CharField(max_length=255, unique=True, validators=[nickName])
    first_name=models.CharField(max_length=255, validators=[firstName])
    last_name=models.CharField(max_length=255, validators=[lastName])
    is_active=models.BooleanField(default=True)  # can login
    is_staff=models.BooleanField(default=False)  # staff user non superuser
    is_admin=models.BooleanField(default=False)  # superuser
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    objects=MyUserManager()

    USERNAME_FIELD='nick'  # username
    REQUIRED_FIELDS=["first_name", "last_name", ]

    def __str__(self):
        return "{}{}".format(self.first_name, self.last_name)

    def full_name(self):
        return "{} {}".format(self.first_name, self.last_name).title()

    @staticmethod
    def has_perm(perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    @staticmethod
    def has_module_perms(app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


# Create your models here.
class calculatorHistory(models.Model):
    input=models.CharField(max_length=250)
    result=models.CharField(max_length=250)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now_add=True, )

    def __str__(self):
        return self.input

    def delete_history(self):
        return reverse("accounts:delete_history", kwargs={"id": self.id})

accounts/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.core.validators import RegexValidator
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import User


class UserCacheMixin:
    user_cache=None
    userType=None
    user_name=None


validators=RegexValidator("^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}$",
                          message="Minimum eight characters, at least one uppercase letter, "
                                  "one lowercase letter and one number:")


class RegistrationForm(forms.ModelForm):
    password1=forms.CharField(label=_('Password'), widget=forms.PasswordInput, validators=[validators])
    password2=forms.CharField(label=_('Password confirmation'), widget=forms.PasswordInput, validators=[validators])

    class Meta:
        model=User
        fields=("nick", 'first_name', "last_name")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean_password2(self):
        # Check that the two password entries match
        password1=self.cleaned_data.get("password1")
        password2=self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(_("Passwords don't match"))

        password_validation.validate_password(password1)

        return password2





class SignIn(UserCacheMixin, forms.Form):
    password=forms.CharField(label=_('Password'), strip=False,
                             widget=forms.PasswordInput()
                             )

    def clean_password(self):
        password=self.cleaned_data.get('password')
        if not self.user_cache:
            return password

        if not self.user_cache.check_password(password):
            raise ValidationError(_('You email or password invalid.'))

        return password


class SignInForm(SignIn):
    nick=forms.CharField(label=_('nick'), )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request=kwargs["initial"]["request"]

    @property
    def field_order(self):
        return ['nick', 'password', ]

    def clean_nick(self):
        nick=self.cleaned_data.get('nick')
        user=User.objects.filter(nick=nick).first()
        if not user:
            raise ValidationError(_('You email or password invalid.'))
        self.user_cache=user
        return nick


class ChangeProfileForm(forms.ModelForm):
    password=forms.CharField(label=_('Password'), widget=forms.PasswordInput, validators=[validators], required=False)

    class Meta:
        model=User
        fields=('first_name', "last_name", "password")


class Calculator(forms.Form):
    input=forms.CharField(max_length=250, label="Expiration")
    result=forms.CharField(max_length=250, required=False)

accounts/templatetags/forms.py
from django import template
from django.conf import settings

register=template.Library()


@register.filter(name='HtmlField')
def HtmlField(field, otherCss=None):
    # do not forget to put space at the end
    css="form-input "
    if otherCss:
        css=css + otherCss
    field.field.widget.attrs.update({'class': css})
    # print(field)
    return field


@register.filter(name='companyError')
def companyError(strings):
    return 'company/handle/company_errors/' + str(strings) + ".html"


@register.simple_tag
def to_list(field):
    return field.split(',')


@register.simple_tag
def formset(index, name):
    names=name.split(',')
    return str(",".join([f"form-{index}-{name}" for name in names]))


@register.filter(name='contain')
def contain(value, sub):
    return True if str(value).count(sub) > 0 else False


@register.filter(name='test')
def test(o):
    # print(((o.nav.amare)))
    # print(o.resolver_match.url_name)
    # 'app_name', 'app_names', 'args', 'func', 'kwargs', 'namespace', 'namespaces', 'route', 'url_name', 'view_name'
    return o


@register.filter(name='testit')
def testit(o):
    return o


@register.simple_tag(takes_context=True)
def param_replace(context, **kwargs):
    d=context['request'].GET.copy()
    for k, v in kwargs.items():
        d[k]=v
    for k in [k for k, v in d.items() if not v]:
        del d[k]
    return d.urlencode()


@register.simple_tag(takes_context=True)
def is_active(context, value):
    request=context['request']
    try:
        s=request.resolver_match.app_names[0] + ":" + request.resolver_match.url_name
    except Exception as e:
        s=""

    if s == value:
        return "bg-white text-black px-2"
    else:
        return "text-white"


@register.simple_tag
def settings_value(name):
    x=getattr(settings, name, "loading...")
    return x

accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    logout_then_login
)
from django.shortcuts import redirect, reverse, render
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import View, FormView, ListView

from accounts.forms import RegistrationForm, Calculator, ChangeProfileForm, SignInForm
# Good 1
from accounts.models import calculatorHistory


class GuestOnlyView(View):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(settings.LOGIN_REDIRECT_URL)
        return super().dispatch(request, *args, **kwargs)


class SignUpView(GuestOnlyView, FormView):
    template_name='accounts/sign_up.html'
    form_class=RegistrationForm

    def form_valid(self, form):
        # collect the user information
        user=form.save(commit=False)
        password=form.cleaned_data.get("password1")
        user.set_password(password)
        user.save()
        messages.success(self.request, _(' successfully Sin up .'))

        return redirect(reverse("accounts:login"))


# Good 5
class LogInView(GuestOnlyView, FormView):
    template_name='accounts/login.html'
    form_class=SignInForm

    def get_initial(self):
        initial=super().get_initial()
        initial['request']=self.request
        return initial

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    # @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        request=self.request
        if request.session.test_cookie_worked():
            request.session.delete_test_cookie()

        login(request, form.user_cache)
        messages.success(self.request, _(f'welcome {self.request.user.full_name()}.'))

        return redirect(reverse("accounts:home"))


class LogOutView(LoginRequiredMixin, View):
    def post(self, request):
        messages.success(self.request, _(' successfully Log out.'))

        logout_then_login(request)
        return redirect(reverse("accounts:login"))


class Home(LoginRequiredMixin, FormView):
    template_name='accounts/home.html'
    form_class=Calculator

    def form_valid(self, form):
        user_input=form.cleaned_data.get("input")
        try:
            result=eval(user_input)

        except Exception as e:
            if str(e).find("(<string>, line 1)") > -1:
                result='Is not Mathematical input'
            else:
                # in order to use some math syntax like 1>0 ,2*(2+43)>5
                result=str(e)
        # in order to prevent print() built in function
        finalResult=result if result is not None else 'Is not Mathematical input'

        calculatorHistory.objects.create(
            user=self.request.user,
            input=user_input,
            result=finalResult

        )
        return render(self.request, "accounts/home.html", {
            "form": Calculator(initial={"input": user_input, "result": finalResult})
        })


class userHistory(LoginRequiredMixin, ListView):
    template_name='accounts/userHistory.html'

    # specify the model for list view
    model=calculatorHistory

    def get_queryset(self, *args, **kwargs):
        qs=super(userHistory, self).get_queryset(*args, **kwargs)
        qs=qs.filter(user=self.request.user).order_by("-id")
        return qs


@login_required
def ProfileView(request):
    template_name='accounts/your_profile.html'
    return render(request, template_name)


@login_required
def deleteHistory(request, id):
    history=calculatorHistory.objects.filter(user=request.user, id=id)
    if history.exists():
        history.delete()
        messages.success(request, _('History  has been successfully Deleted.'))
    else:
        messages.success(request, _('Sorry this history is not exist'))

    return redirect(reverse("accounts:history"))


@login_required
def deleteAllHistory(request, ):
    history=calculatorHistory.objects.filter(user=request.user)
    if history.exists():
        history.delete()
        messages.success(request, _('All History  has been successfully Deleted.'))
    else:
        messages.warning(request, _('Sorry there is  history to delete'))
    return redirect(reverse("accounts:history"))


class ChangeProfileView(LoginRequiredMixin, FormView):
    template_name='accounts/change_profile.html'
    form_class=ChangeProfileForm

    def get_form_kwargs(self):
        kwargs=super(ChangeProfileView, self).get_form_kwargs()
        kwargs.update({'instance': self.request.user})
        kwargs.update({'initial': {"password": ""}})
        return kwargs

    def form_valid(self, form):
        user=form.save(commit=False)
        password=form.cleaned_data.get("password", None)
        if password is not None:
            user.set_password(password)
            update_session_auth_hash(self.request, user)
        user.save()
        messages.warning(self.request, _('Profile  has been successfully updated.'))

        return redirect('accounts:profile')

accounts/templates/accounts/change_profile.html
{% extends 'base.html' %}

{% load i18n %}
{% block content %}

<div class="container mx-auto   ">

    <div class="flex flex-wrap justify-center sm:mt-16">
        <div class="w-full max-w-sm">
            <div class="flex flex-col break-words bg-white border border-2 rounded shadow-md">

                <div class="font-semibold bg-gray-200 text-teal-700 py-3 px-6 mb-0">
                    {% trans 'Change profile' %}

                </div>

                <form class="w-full p-4" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="flex justify-center">
                        {% if request.user.info.image %}
                        <img class=" h-20 w-20 bg-cover rounded-full" src="{{ request.user.info.image.url }}">
                        {% endif %}
                    </div>

                    {% include "form/form.html" with form=form only="first_name,last_name,password" %}

                    {% trans 'Change' as btn %}

                    {% include "form/btn.html" with name="Change" center="True" %}


                </form>

            </div>
        </div>
    </div>
</div>


{% endblock %}

accounts/templates/accounts/home.html
{% extends 'base.html' %}

{% load forms %}
{% load i18n %}

{% block content %}

<div>

    <div class="flex flex-wrap justify-center mt-4 sm:mt-6 md:mt-10 px-2 md:px-0">
        <div class="w-full max-w-xl">
            <div class="flex flex-col break-words bg-white border border-2 rounded shadow-md">

                <div class="font-semibold bg-gray-200 text-teal-700 py-3 px-6 mb-0 text-base">
                    Calculate
                </div>

                <form class="w-full p-4" method="POST">
                    {% csrf_token %}
                    {% include "form/form.html" with form=form only='input' %}
                    <div class="flex flex-col mt-2">
                        <p class="text-md font-semibold text-center">You can input:</p>
                        <p>
                        <ul>
                            <li> => 12*(2021/(12))+112-12+(34/5) .....................2127.8</li>
                            <li> => 12>89......................................False</li>
                            <li> => 2*(4+2) >=(3*4)/2 ..........................True</li>
                        </ul>
                        </p>


                    </div>
                    {% include "form/form.html" with form=form only='result' %}
                    {% include "form/btn.html" with name="Calculate" center=True %}

                </form>

            </div>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load forms %}
{% load i18n %}

{% block content %}

<div>

    <div class="flex flex-wrap justify-center mt-4 sm:mt-6 md:mt-10 px-2 md:px-0">
        <div class="w-full max-w-sm">
            <div class="flex flex-col break-words bg-white border border-2 rounded shadow-md">

                <div class="font-semibold bg-gray-200 text-teal-700 py-3 px-6 mb-0 text-base">
                    Login
                </div>

                <form class="w-full p-4" method="POST">
                    {% csrf_token %}
                    {% include "form/form.html" with form=form only='nick,password' %}

                    {% include "form/btn.html" with center="True" name="Login" %}

                    <div class="flex flex-wrap items-center">



                        <p class="w-full text-xs text-center text-gray-700 mt-4 ">
                            {% url 'accounts:sign_up' as the_url %}
                            {% trans "Don't have an account ?" %} <a
                                class="text-blue-500 hover:text-blue-700 no-underline"
                                href="{{ the_url }}">
                            {% trans "Register" %} </a>
                        </p>

                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Logged out</h1>
    <p>
        You have logged out!
    </p>
</div>
{% endblock %}

accounts/templates/accounts/sign_up.html
{% extends 'base.html' %}
{% load  i18n %}

{% block content %}

<div id='app'>


    <div class="flex flex-wrap justify-center mt-6">
        <div class="w-full max-w-sm px-2 md:px-0">
            <div class="flex flex-col bg-white border border-2 rounded shadow-md">
                <div class="font-semibold bg-gray-200 text-teal-700 py-3 px-6 ">
                    {% trans 'Register' %}
                </div>
                <form class="p-2" method="POST">
                    {% csrf_token %}
                    {% include "form/form.html" with form=form only='nick' %}
                    {% include "form/formRow.html" with form=form field='first_name,last_name' %}
                    {% include "form/form.html" with form=form only='email,phone' %}
                    {% include "form/form.html" with form=form only='password1,password2' %}


                    <div class="flex flex-wrap items-center">
                        {% trans 'Sign Up' as btn %}

                                                {% include "form/btn.html" with name=btn %}

                        {% url 'accounts:restore_password' as the_url %}

                        <p class="w-full text-xs text-center text-gray-700 mt-4 ">
                            {% url 'accounts:login' as the_url %}
                            {% trans ' I have an account already' %}
                            <a class="text-blue-500 hover:text-blue-700 no-underline" href="{{ the_url }}">

                                {% trans 'Login' %}
                            </a>
                        </p>

                    </div>


                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block  js %}

{% endblock %}

accounts/templates/accounts/userHistory.html
{% extends 'base.html' %}

{% load forms %}
{% load i18n %}
{% load humanize %}

{% block content %}

<div>

    <div class="flex flex-wrap justify-center mt-4 sm:mt-6 md:mt-10 px-2 md:px-0">
        <div class="w-3/4">
            <div class="flex flex-col break-words bg-white border border-2 rounded shadow-md w-full w-1/2">

                <div class="font-semibold bg-gray-200 text-teal-700 py-3 px-6 mb-0 text-base">
                    Calculate
                </div>
                <div class="flex mb-4">
                    <div class="w-3/5 font-extrabold ml-6">
                        Expiration
                    </div>
                    <div class="w-1/5 font-extrabold">
                        Result
                    </div>

                    <div class="w-1/5 font-extrabold">
                        time
                    </div>
                    <div class="w-1/5 font-extrabold">
                        {%url "accounts:delete_all_history" as the_url%}
                        <a href="{{the_url}}" class="bg-red-400 px-2 text-white"> Delete All </a>
                    </div>

                </div>
                {% for object in object_list %}

                <div class="flex mb-4">
                    <div class="w-3/5 font-medium text-xl ml-6">
                        {{object.input}}
                    </div>
                    <div class="w-1/5 font-medium">
                        {{object.result}}
                    </div>

                    <div class="w-1/5 font-medium">
                        {{ object.created_at|naturaltime }}
                    </div>
                    <div class="w-1/5 font-medium">


                        <a href="{{ object.delete_history}}" class="bg-red-400 px-2 text-white"> Delete</a>

                    </div>
                </div>
                {% empty %}
                <li>No objects yet.</li>
                {% endfor %}


            </div>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/your_profile.html
{% extends 'base.html' %}
{% load  i18n %}

{% block content %}

<div class=" mt-32 bg-gray-500 shadow overflow-hidden sm:rounded-lg flex flex-wrap md:justify-center py-2 md:py-6">
    <div class=" 12 px-4 py-5 sm:px-6 w-full sm:w-1/6">
        <h3 class="text-xl leading-6 font-medium  text-center text-gray-100 ">
            Your profile Information
        </h3>
        <div class="flex justify-center pt-2 sm:pt-4 ">
            {% if request.user.info.image %}
            <img class=" h-20 w-20 md:h-32  md:w-32  bg-cover rounded-full" src="{{ request.user.info.image.url }}">
            {% endif %}
        </div>

    </div>
    <div class="border-t border-gray-200 w-full sm:w-3/6">
        <dl>
            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Nick
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{user.nick}}
                </dd>
            </div>
            <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    First Name
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{user.first_name}}
                </dd>
            </div>
            <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Last Name
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{user.last_name}}

                </dd>
            </div>


        </dl>
        <div class="flex justify-center pt-3 ">
            {%url 'accounts:change_profile' as the_url%}
            <a href="{{the_url}}" class="btn">Change</a>
        </div>
    </div>


</div>
{% endblock %}

{% block  js %}

{% endblock %}