accounts/urls.py
from django.urls import path

from .views import (
    LogInView, SignUpView, LogOutView,
    ProfileView, Home, userHistory, ChangeProfileView, deleteHistory, deleteAllHistory)

app_name="accounts"

urlpatterns=[

    path('', LogInView.as_view(), name='login'),
    path('login/', LogInView.as_view(), name='login'),
    path('log-out/', LogOutView.as_view(), name='logout'),
    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('home/', Home.as_view(), name='home'),
    path('userHistory/', userHistory.as_view(), name='history'),
    path('deleteHistory/<id>/', deleteHistory, name='delete_history'),
    path('deleteAllHistory/', deleteAllHistory, name='delete_all_history'),
    path('profile/', ProfileView, name='profile'),
    path('change_profile/', ChangeProfileView.as_view(), name='change_profile'),

]

django_calculator/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve

from accounts.views import LogInView, SignUpView, Home

urlpatterns=[
    path('', LogInView.as_view(), name='login'),
    path('login/', LogInView.as_view(), name='login'),
    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('home/', Home.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),

    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

templates/nav/authUser.html
<div class="hidden md:block">
    <div class="ml-4 flex items-center md:ml-6">

        <!-- Profile dropdown -->
        <div class="ml-3 relative">
            <div>
                <a href="#"
                   class=" block px-4 py-2 text-sm text-gray-700 bg-gray-100 no-underline  text-gray-300 text-sm p-3"
                   onclick="event.preventDefault();
                                    document.getElementById('logout-form').submit();">Log Out</a>
                {%url 'accounts:logout' as the_url%}

                <form id="logout-form" action="{{the_url}}" method="POST" class="hidden">
                    {% csrf_token %}

                </form>
        </div>
    </div>
</div>
</div>

templates/nav/mainNav.html
{% load forms %}
<div class="ml-10 flex items-baseline space-x-4 ">


    {% is_active "tickets:localFightList" as is_active%}
    {% url 'tickets:localFightList' as the_url %}
    {% if user.is_authenticated%}
    {% url 'accounts:home' as the_url %}
    {% is_active "accounts:home" as is_active%}

    <a href="{{the_url}}"
       class="{{is_active}}  py-2 rounded-md text-sm font-medium  hover:bg-gray-200 hover:text-black ">calculator page
    </a>
    {% url 'accounts:history' as the_url %}

    {% is_active "accounts:history" as is_active%}

    <a href="{{the_url}}"
       class="{{is_active}}  py-2 rounded-md text-sm font-medium  hover:bg-gray-200 hover:text-black ">History page
    </a>
    {% url 'accounts:profile' as the_url %}

    {% is_active "accounts:profile" as is_active%}

    <a href="{{the_url}}"
       class="{{is_active}}  py-2 rounded-md text-sm font-medium  hover:bg-gray-200 hover:text-black ">User profile
    </a>

{% url 'accounts:change_profile' as the_url %}

    {% is_active "accounts:change_profile" as is_active%}

    <a href="{{the_url}}"
       class="{{is_active}}  py-2 rounded-md text-sm font-medium  hover:bg-gray-200 hover:text-black ">Change Profile
    </a>
    {%endif%}

</div>

templates/nav/nav.html
<!-- This example requires Tailwind CSS v2.0+ -->
{%load forms%}
{% if user.is_authenticated%}
<div id="nav" class="md:fixed md:top-0 w-full">
    <nav class="bg-gray-600">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex items-center justify-between h-16">
                <div class="flex items-center">
                    <div class="flex-shrink-0" style="font-family: 'Baloo Tamma 2', cursive;">

                    </div>
                    {% include "nav/mainNav.html" %}
                </div>
                {% if user.is_authenticated%}
                {% include "nav/authUser.html" %}
                {%endif%}

            </div>
        </div>


    </nav>


</div>
{%endif%}

templates/nav/openCloseButton.html
<div class="-mr-2 flex md:hidden">
    <!-- Mobile menu button -->
    <button type="button" @click="isOnMenu = !isOnMenu"
            class="bg-gray-600 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white"
            aria-controls="mobile-menu" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <!--
          Heroicon name: outline/menu

          Menu open: "hidden", Menu closed: "block"
        -->
        <svg :class="isOnMenu ? 'hidden' : ' block'" class=" h-6 w-6"
             xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
             stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M4 6h16M4 12h16M4 18h16"/>
        </svg>
        <!--
          Heroicon name: outline/x

          Menu open: "block", Menu closed: "hidden"

        -->
        <svg :class="isOnMenu ? 'block' : ' hidden'" class=" h-6 w-6" xmlns="http://www.w3.org/2000/svg"
             fill="none" viewBox="0 0 24 24"
             stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                  d="M6 18L18 6M6 6l12 12"/>
        </svg>
    </button>
</div>